# Generated by Django 3.2.8 on 2021-12-07 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_personaldashboard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldashboard',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='personaldashboard',
            unique_together={('name', 'user')},
        ),
    ]
