# Generated by Django 3.2.8 on 2021-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211207_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldashboard',
            name='type_of_pd',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('TASK', 'Task'), ('NOTE', 'Note')], default='TASK', max_length=7),
        ),
    ]
