# Generated by Django 3.2.8 on 2021-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_personaldashboard_type_of_pd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldashboard',
            name='name',
            field=models.CharField(default='NONAME', max_length=10),
        ),
    ]
