# Generated by Django 3.2.8 on 2021-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_personaldashboard_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
