# Generated by Django 3.2.8 on 2021-12-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_drawing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='drawing',
            field=models.TextField(),
        ),
    ]
